#!/bin/bash


# beam server
#CFLAGS="-I/opt/hdf5/1.8.20/include"
#LDFLAGS="-L/opt/hdf5/1.8.20/lib"

# PAL ubuntu
#CFLAGS="-I/usr/lib/x86_64-linux-gnu/hdf5/openmpi/include" 
#LDFLAGS="-L/usr/lib/x86_64-linux-gnu/hdf5/openmpi" 

# server
#CFLAGS = "-I/opt/gsl/2.6/include -I/opt/fftw/3.3.8/include -I/opt/hdf5/1.10.3/include"
#LDFLAGS = "-L/opt/gsl/2.6/lib -L/opt/fftw/3.3.8/lib -L/opt/hdf5/1.10.3/lib"

CFLAGS="-I/opt/hdf5/1.14.5/include -I/opt/gsl/2.8/include"
LDFLAGS="-L/opt/hdf5/1.14.5/lib -L/opt/gsl/2.8/lib"


gcc -o fft fft.c -lm
echo 'fft is made.'

gcc -o centerField centerField.c -lm
echo 'centerField is made.'

mpicc -o field_cylind hdf_field_cylindrical.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'field_cylind is made.'

mpicc -o field_cart hdf_field_cartesian.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'field_cart is made.'

mpicc -o hdf_particle hdf_particle.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'hdf_particle is made.'

gcc -o emittance emittance.c -lm
echo 'emittance is made.'

mpicc -o track track.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'track is made.'

mpicc -o particle particle.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'particle is made.'

mpicc -o sync ${CFLAGS} ${LDFLAGS} sync.c -lm -lhdf5 -lgsl -lgslcblas 
#mpicc -o sync sync20221216.c -lm -lhdf5 ${CFLAGS} ${LDFLAGS}
echo 'sync is made.'

